export const mapUser = (u) => ({
  id: u.id,
  name: u.display_name || u.username,
  handle: u.username,
  avatar: u.avatar,
  email: u.email || "",
  country: u.country_code || "",
  color: "#49dcc8",
  status: "offline",
  bio: "",
  level: 0,
  points: 0,
  wallet: Number(u.wallet_balance || 0),
  role: "player",
});
export const mapGame = (g) => ({
  storeVisible: g.storeVisible ?? true,
  id: g.slug,
  apiId: g.id,
  title: g.title,
  tagline: g.short_description,
  description: g.description || g.short_description,
  image: g.cover_image || "",
  color: "#234745",
  price: Number(g.price),
  discount: g.discount_percent,
  finalPrice: Number(g.final_price),
  genre: g.genres?.map((x) => x.name).join(", ") || "Без жанра",
  tags: g.tags?.map((x) => x.name) || [],
  developer: g.developers?.map((x) => x.name).join(", ") || "",
  hours: 0,
  rating: null,
  achievements: 0,
  totalAchievements: 0,
  screenshots: g.screenshots || [],
  requirements: g.requirements,
});
export const emptyState = () => ({
  active: null,
  users: [],
  friends: [],
  messages: [],
  reviews: [],
  orders: [],
  cart: {},
  wishlist: {},
  library: {},
  settings: {},
  comparison: {},
  notifications: [],
  announcement: { enabled: false },
  collections: [],
  parties: [],
  posts: [],
  comments: [],
  mods: [],
  activity: [],
  events: [],
  reports: [],
  tickets: [],
  gifts: [],
  walletLog: [],
  pointsLog: [],
  cosmeticsOwned: {},
  saleWatch: {},
  adminLog: [],
});
