# Generated by Django 5.2.11 on 2026-09-22 13:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_game_options_alter_game_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_preorder',
            field=models.BooleanField(default=False, help_text='Запись в библиотеке ожидает релиза. Снимите флажок после выхода игры.', verbose_name='Предзаказ'),
        ),
        migrations.AddField(
            model_name='game',
            name='official_url',
            field=models.URLField(blank=True, verbose_name='Официальная страница'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.CharField(blank=True, max_length=200, verbose_name='Платформы'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='game_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__lte', 100)), name='game_discount_at_most_100'),
        ),
    ]
