# Generated by Django 5.2.11 on 2026-09-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_game_is_preorder_game_official_url_game_platforms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemrequirement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Дополнительные требования'),
        ),
    ]
