# Generated by Django 5.2.11 on 2026-09-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_protect_gift_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_preorder',
            field=models.BooleanField(default=False),
        ),
    ]
