# Generated by Django 5.2.11 on 2026-09-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_community_economy_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationWindow',
            fields=[
                ('identity', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
            ],
        ),
    ]
